### PR TITLE
Modify _get_repo_name to use C locale when runing git

### PR DESCRIPTION
**Pull request by jluis**
The outoput of git depends on the curren locale and he current regex only works on some of them

Signed-off-by: Jose Luis Perez Diez <jluis@escomposlinux.org>

### CODE REVIEW

**Comment by karenetheridge** [comment]
interesting -- what locale failed for you? I'd like to reproduce this as it may affect some of my other modules as well.

**Comment by jluis** [comment]
I'm usig LANG=ca_ES.UTF-8 but it should fail in other locales too I did a similar path on Minilla during  last year CPAN pull request challenge (https://github.com/tokuhirom/Minilla/issues/176) .

A quick `git grep -C4 'Fetch URL: ' ./po/`on git git shows that it should fail also on  bg,de,ko,ru,sv,vi and zn_CN
 
I haven't seen any other places that would need to change the locale but I only used grep git ./ to find points of failure  I was assigned with Text::CSV::Encoded this month I found the bug when building the disto.

**Comment by karenetheridge** [comment]
interesting, tests still pass for me:

```
: [ether@jaeger git/Dist-Zilla-Plugin-GitHub].0$; export LANG=ca_ES.UTF-8
: [ether@jaeger git/Dist-Zilla-Plugin-GitHub].0$; locale
LANG="ca_ES.UTF-8"
LC_COLLATE="ca_ES.UTF-8"
LC_CTYPE="ca_ES.UTF-8"
LC_MESSAGES="ca_ES.UTF-8"
LC_MONETARY="ca_ES.UTF-8"
LC_NUMERIC="ca_ES.UTF-8"
LC_TIME="ca_ES.UTF-8"
LC_ALL=

: [ether@jaeger git/Dist-Zilla-Plugin-GitHub].0$; date
dimecres, 27 de gener de 2016, 11:25:01 PST

: [ether@jaeger git/Dist-Zilla-Plugin-GitHub].0$; git describe
v0.41-4-gd08bc33

: [ether@jaeger git/Dist-Zilla-Plugin-GitHub].0$; prove -lr t
t/01-update.t .. ok   
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.67 cusr  0.05 csys =  0.74 CPU)
Result: PASS
```

**Comment by karenetheridge** [comment]
What different output does git give when you are using your native locale?  `git remote` looks the same to me:

```
: [ether@jaeger git/Dist-Zilla-Plugin-GitHub].0$; LANG=ca_ES.UTF-8 git remote show -n origin
* remote origin
  Fetch URL: git@github.com:ghedo/p5-Dist-Zilla-Plugin-GitHub.git
  Push  URL: git@github.com:ghedo/p5-Dist-Zilla-Plugin-GitHub.git
  HEAD branch: (not queried)
  Remote branches: (status not queried)
    master
    pr/10
    pr/13
    pr/16
    pr/17
    pr/18
    pr/19
    pr/20
    pr/26
    pr/27
    pr/30
    pr/33
    pr/34
    pr/36
    pr/37
    pr/39
    pr/40
    pr/41
    pr/44
    pr/45
    pr/46
    pr/47
    pr/48
    pr/7
  Local branches configured for 'git pull':
    autarch/no-pointless-update rebases onto remote autarch/no-pointless-update
    master                      rebases onto remote master
  Local ref configured for 'git push' (status not queried):
    (matching) pushes to (matching)
```

**Comment by karenetheridge** [comment]
I still want to reproduce the locale issue, but I suspect the real fix ought to live on Git::Wrapper, rather than here.

**Comment by karenetheridge** [comment]
Weird, setting `LANG` does work, but only when I'm not inside a screen session.  It's as if screen is somehow overriding my setting of LANG.

**Comment by jluis** [comment]
my output from this fresh cloned repo:
```
 jluis@debianhill:~/p5-Dist-Zilla-Plugin-GitHub$ LANG=ca_ES.UTF-8 git remote show -n origin
* remot origin
  URL d'obteniment: https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub
  URL de pujada: https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub
  Rama de HEAD: (not queried)
  Rama remota: (estat no consultat)
    master
  Rama local configurada per a 'git pull':
    master es fusiona amb el remot master
  Referència local configurada per a 'git push' (estat no consultat):
   (coincident) puja a (coincident)jluis@debianhill:~/p5-Dist-Zilla-Plugin-GitHub$ LANG=C git remote show -n origin
* remote origin
  Fetch URL: https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub
  Push  URL: https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub
  HEAD branch: (not queried)
  Remote branch: (status not queried)
    master
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push' (status not queried):
    (matching) pushes to (matching)

jluis@debianhill:~/p5-Dist-Zilla-Plugin-GitHub$ LANG=bg_BG.UTF8 git remote show -n origin
● отдалечено хранилище „origin“
  Адрес за доставяне: https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub
  Адрес за изтласкване: https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub
  клон сочен от HEAD: (not queried)
  Отдалечен клон: (състоянието не бе проверено)
    master
  Локален клон настроен за издърпване чрез „git pull“:
    master сливане с отдалечения клон „master“
  Локалният указател, настроен за „git push“ (състоянието не бе проверено):
    (съвпадащи) изтласква към (съвпадащи)

```

For me works even when using screen

**Comment by karenetheridge** [comment]
Thanks, merged and released!

**Pull request closed without merging**
